version: "3.1"

services:
  # APP
  app:
    container_name: 2faces-backend_app
    restart: always
    env_file: .env
    build: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_MAIN_PORT}:${SOCKET_MAIN_PORT}"
      - "52000-52500:52000-52500"
      - "60000-60100:60000-60100"
    depends_on:
      - mongo
    links:
      - mongo

  # PANEL
#  panel:
#    container_name: 2faces-panel
#    image: 2faces-panel:latest
#    restart: always
#    ports:
#      - "9001:9001"
#    depends_on:
#      - app
#    links:
#      - app

  # MongoDB
  mongo:
    container_name: 2faces-backend_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"

  # MongoDB Dump
  mongodump:
    container_name: 2faces-backend_mongo_dump
    env_file: .env
    build: dump/
    depends_on:
      - mongo
    links:
      - mongo
