version: "3.2"

services:
  # APP
  app:
    container_name: 2faces-backend_app
    restart: always
    env_file: .env
    build: ./app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_MAIN_PORT}:${SOCKET_MAIN_PORT}"
      - "52000-52500:52000-52500"
      - "40000-40100:40000-40100"
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB
  mongo:
    container_name: 2faces-backend_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - "./mongo:/docker-entrypoint-initdb.d"

volumes:
  mongo-init:
    driver: local
