version: "3.1"

services:
  # APP
  app:
    container_name: 2faces-backend_app
    restart: always
    env_file: .env
    build: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_MASTER_PORT}:${SOCKET_MASTER_PORT}"
      - "52000-52500:52000-52500"
      - "60000-60100:60000-60100"
    volumes:
      - .:/app
    depends_on:
      - mongo
    links:
      - mongo

  # MongoExpress
  mongo-express:
    container_name: 2faces-backend_mongo-express
    image: mongo-express:latest
    restart: always
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB
  mongo:
    container_name: 2faces-backend_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - './mongo-init/:/docker-entrypoint-initdb.d/'
